# Generated by Django 2.0.7 on 2020-05-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0002_auto_20200524_1059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Dog',
        ),
    ]
