# Generated by Django 2.0.7 on 2020-05-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0003_auto_20200524_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='date',
        ),
        migrations.AddField(
            model_name='dog',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
